name: Deploy Main to S3 Production
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: sleavely/node-awscli:14.x
    steps:
    - uses: actions/checkout@v2
    - run: sed -i 's/staging.api.footlight.io/api.footlight.io/g' index.html
    - run: sed -i 's/staging.api.footlight.io/api.footlight.io/g' organizations/search-orgs.html
    - run: sed -i 's/staging.api.footlight.io/api.footlight.io/g' events/search-events.html
    - run: sed -i 's/staging.api.footlight.io/api.footlight.io/g' footlightApi.js
    - run: sed -i 's/concept=635fa2ab7086d70059aca2bc/concept=63d167da016e830064fbb03b/g' footlightApi.js
    - run: sed -i 's/63bf164443d51e00705e349e/63b861f21c6b6c005aad483b/g' places/places.js
    - run: sed -i 's/63bf164443d51e00705e349e/63b861f21c6b6c005aad483b/g' places/places.js
    - run: aws s3 sync . s3://demo.tout-culture --acl public-read --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        AWS_REGION: ca-central-1 
        WEBHOSTING_BUCKET_NAME: demo.tout-culture